### ISSUE TITLE
features.py missing

### ISSUE THREAD

**Issue by wendlerc** [alfred-tarski/latticeconv#1]
Hi,

I have been trying to run your experiment. However features.py seems to be missing.

Kind regards,
Chris

**Comment by alfred-tarski** [comment]
Hello,

Thanks for reaching out.  I forgot to add it. My apologies. Please let me know if you need anything else.

Hans

**Comment by alfred-tarski** [comment]
I should also mention that processing the data can take a *very* long time with RIVET. Just keep that in mind if you are trying to run something before reviews are due. Also, I probably should have mentioned that I ran RIVET with a aws ubuntu ec2 instance, not sure if RIVET is compatible with windows or iOS.

**Comment by wendlerc** [comment]
I was just about to ask you whether you could be so kind and upload your preprocessed data. At the moment I got another issue... apparently the files 'rivet_get_features.py' and 'rivet.py' are incompatible:

```
Traceback (most recent call last):
  File "rivet_get_features.py", line 29, in <module>
    write_rivet_input(point_cloud,density_filtration,k,max_dist,name)
TypeError: write_rivet_input() takes 4 positional arguments but 5 were given
```

UPDATE: I changed the calls in rivet_get_features.py to match the signature of rivet.py and now it does something.

**Comment by alfred-tarski** [comment]
Ok. Hold on. I am dropping and dragging since I don't want to compromise the double-blindness ;) only letting me upload 100 at a time.

**Comment by wendlerc** [comment]
Someone already violated your double blindness by citing you by name in the Quiver Signal Processing preprint.

**Comment by alfred-tarski** [comment]
Oops. Thanks for pointing this out. I uploaded the preprocessed data contained in /invariants

**Comment by wendlerc** [comment]
thank you very much :)
